version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: propelize_backend
    command: gunicorn propelize.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./propelize:/app/propelize
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=propelize.settings
      - DJANGO_SECRET_KEY=dev-secret
      - DEBUG=True
    depends_on: []
    networks:
      - propelize_net

  frontend:
    image: node:20
    container_name: propelize_frontend
    working_dir: /app/PropelizeFrontend
    volumes:
      - ./PropelizeFrontend:/app/PropelizeFrontend
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - propelize_net

networks:
  propelize_net:
    driver: bridge

