# Generated by Django 5.2 on 2025-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=127)),
                ('make', models.TextField()),
                ('model', models.CharField(max_length=127)),
                ('year', models.PositiveIntegerField()),
                ('rentalprice', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
