# Generated by Django 5.2 on 2025-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicule",
            name="registration_number",
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
