name: CI & Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: propelize
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov

      - name: Check Python formatting (black)
        run: |
          pip install black
          black --check .

      - name: Lint Python code (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Security check (bandit)
        run: |
          pip install bandit
          bandit -r .

      - name: Run Django tests with coverage and generate junit report
        run: |
          pytest --cov=propelize --junitxml=reports/junit.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: propelize/test-results/

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: backend-junit-report
          path: propelize/reports/junit.xml

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PropelizeFrontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check formatting (Prettier)
        run: npx prettier --check .

      - name: Lint JS/TS code (ESLint)
        run: npx eslint .

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: PropelizeFrontend
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60

      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: frontend-test-results
          path: PropelizeFrontend/cypress/results/

  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and test Docker image
        run: |
          docker build -t propelize .
          docker run --rm propelize python manage.py migrate
          docker run --rm propelize python manage.py test

      - name: Run Docker Compose tests
        run: docker compose up --build --abort-on-container-exit

      - name: Stop Docker Compose and clean
        run: |
          docker compose down
          docker system prune -f

      - name: Save container logs
        run: |
          mkdir -p docker-test-results
          docker logs propelize_web_1 > docker-test-results/web.log || true
          docker logs propelize_db_1 > docker-test-results/db.log || true
          docker logs propelize_redis_1 > docker-test-results/redis.log || true
          docker logs propelize_celery_1 > docker-test-results/celery.log || true
          docker logs propelize_celery-beat_1 > docker-test-results/celery-beat.log || true

      - name: Check Docker image and containers
        run: |
          docker images
          docker ps -a

      - name: Check Docker Compose status and logs
        run: |
          docker compose ps
          docker compose logs
          docker compose config
          docker compose version

      - name: Upload Docker test results and logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: docker-test-results
          path: docker-test-results/
